engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  duplication:
    enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- lib/
- test/
- template/assets/
