export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';

export const FETCH_BOOKS_COMPLETE = 'FETCH_BOOKS_COMPLETE';

export const FETCH_BOOKS_REJECT = 'FETCH_BOOKS_REJECT';

export const FETCH_SINGLE_BOOK_COMPLETE = 'FETCH_SINGLE_BOOK_COMPLETE';

export const FETCH_SINGLE_BOOK_REJECT = 'FETCH_SINGLE_BOOK_REJECT';

export const FETCH_SINGLE_BOOK_HISTORY_COMPLETE =
  'FETCH_SINGLE_BOOK_HISTORY_COMPLETE';

export const FETCH_SINGLE_BOOK_HISTORY_REJECT =
  'FETCH_SINGLE_BOOK_HISTORY_REJECT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CLOUDINARY_CLOUD_URL =
  'https://api.cloudinary.com/v1_1/dmdl6p9mx/upload';

export const CLOUDINARY_UPLOAD_PRESET = 'yk1kf9se';

export const BORROW_SINGLE_BOOK_COMPLETE = 'BORROW_SINGLE_BOOK_COMPLETE';

export const BORROW_SINGLE_BOOK_REJECT = 'BORROW_SINGLE_BOOK_REJECT';

export const RETURN_SINGLE_BOOK_COMPLETE = 'RETURN_SINGLE_BOOK_COMPLETE';

export const RETURN_SINGLE_BOOK_REJECT = 'RETURN_SINGLE_BOOK_REJECT';

export const FETCH_SINGLE_BOOK_INVALID = 'FETCH_SINGLE_BOOK_INVALID';

export const FETCH_BOOK_CLEAR = 'FETCH_BOOK_CLEAR';

export const EDIT_BOOK_COMPLETE = 'EDIT_BOOK_COMPLETE';

export const EDIT_BOOK_ERROR = 'EDIT_BOOK_ERROR';

export const FETCH_BORROWED_BOOKS_HISTORY_COMPLETE =
  'FETCH_BORROWED_BOOKS_HISTORY_COMPLETE';

export const FETCH_BORROWED_BOOKS_HISTORY_REJECT =
  'FETCH_BORROWED_BOOKS_HISTORY_REJECT';

export const HOME_PAGE_BOOKS_COMPLETE =
  'HOME_PAGE_BOOKS_COMPLETE';

export const HOME_PAGE_BOOKS_REJECT =
  'HOME_PAGE_BOOKS_REJECT';

export const AUTHOR_CREATED_SUCCESS =
  'AUTHOR_CREATED_SUCCESS';

export const AUTHOR_CREATED_FAILURE =
  'AUTHOR_CREATED_FAILURE';

export const VERIFY_USER_SUCCESS =
  'VERIFY_USER_SUCCESS';

export const VERIFY_USER_FAILURE =
  'VERIFY_USER_FAILURE';

export const SIGN_IN_UNSUCCESSFUL =
  'SIGN_IN_UNSUCCESSFUL';

export const CATEGORY_CREATE_COMPLETE =
  'CATEGORY_CREATE_COMPLETE';

export const CATEGORY_CREATE_FAILURE =
  'CATEGORY_CREATE_FAILURE';

export const ADD_BOOK_CATEGORY_SUCCESS =
  'ADD_BOOK_CATEGORY_SUCCESS';

export const ADD_BOOK_CATEGORY_FAILURE =
  'ADD_BOOK_CATEGORY_FAILURE';

export const CLEAR_BOOKS =
  'CLEAR_BOOKS';

export const FETCH_BOOKS_INVALID =
  'FETCH_BOOKS_INVALID';

export const VIEW_CATEGORY_LIST_SUCCESS =
  'VIEW_CATEGORY_LIST_SUCCESS';

export const VIEW_CATEGORY_LIST_FAILURE =
  'VIEW_CATEGORY_LIST_FAILURE';

export const DELETE_CATEGORY_SUCCESS =
  'DELETE_CATEGORY_SUCCESS';

export const REMOVE_BOOK_FROM_CATEGORY_SUCCESS =
  'REMOVE_BOOK_FROM_CATEGORY_SUCCESS';

export const LOAD_ALL_BOOKS_SUCCESS =
  'LOAD_ALL_BOOKS_SUCCESS';
